---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Check if htpasswd command is available
      ansible.builtin.shell:
        cmd: command -v htpasswd
      changed_when: false
